---
type: Asset
api_version: core/v2
metadata:
  name: sensu/check-memory-usage:0.2.2
  labels:
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/check-memory-usage
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/check-memory-usage
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 0.2.2
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.name: check-memory-usage
    io.sensu.bonsai.tags: ''
spec:
  builds:
  - url: https://assets.bonsai.sensu.io/e819cf3451eae610a71c2e8b56913a702f8c82b4/check-memory-usage_0.2.2_windows_amd64.tar.gz
    sha512: 90a997a0e8d977e706e56a8d092c1afa3bd66142fbb35b4819c5fc04df41542fdaba711edf3f0b285113630147be7c988f6eeb6b83a861fb5b075a0abe67f0d8
    filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
  - url: https://assets.bonsai.sensu.io/e819cf3451eae610a71c2e8b56913a702f8c82b4/check-memory-usage_0.2.2_darwin_amd64.tar.gz
    sha512: 57ebebeb1c4251c307beb292bb7bb50624aa23c2548eea7cf9ce6a84d14363af6433aadcc103da88c573816065155670ae70a0dfc1f0eeea051ff906dde2f179
    filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
  - url: https://assets.bonsai.sensu.io/e819cf3451eae610a71c2e8b56913a702f8c82b4/check-memory-usage_0.2.2_linux_armv7.tar.gz
    sha512: 6f7d0d2e0a1d1d113f5e881892857ba5833745c2512debdf0afe0e1f85e6baa1c726e78f973d5900d580550a2efd7599ad23a1f4ee4c391a9f597288afe504de
    filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'armv7'
  - url: https://assets.bonsai.sensu.io/e819cf3451eae610a71c2e8b56913a702f8c82b4/check-memory-usage_0.2.2_linux_arm64.tar.gz
    sha512: 94a41f317df0b28fbb3aae86f258e85a0c0e4b346f1429d77404f0fa04568375d9f8f81521d4fa3ae502d063bb937edf289346ac3e3a7abc4c87d01e70d0c27c
    filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
  - url: https://assets.bonsai.sensu.io/e819cf3451eae610a71c2e8b56913a702f8c82b4/check-memory-usage_0.2.2_linux_386.tar.gz
    sha512: 125f9c137fa3940cc72d5a2610b73ba22d5329645ce335da35baaffdbcb57b29431752bc8b6ecc37f79b94ded61833a154a067b8830a6df6c7d141bc55f45731
    filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
  - url: https://assets.bonsai.sensu.io/e819cf3451eae610a71c2e8b56913a702f8c82b4/check-memory-usage_0.2.2_linux_amd64.tar.gz
    sha512: 663985d5c23f4fce1a28d34f582a547390c413acad8d56c67ed103de028acb5d293bbbd9e87b8434ca3193480053399f063d1d67a0cf0299764c5e03f20ff180
    filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'