---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_token
spec:
  provider: vault
  id: secret/sensu/rocketchat#token
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_userid
spec:
  provider: vault
  id: secret/sensu/rocketchat#id
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_user
spec:
  provider: vault
  id: secret/sensu/rocketchat#user
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_password
spec:
  provider: vault
  id: secret/sensu/rocketchat#password
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_url
spec:
  provider: vault
  id: secret/sensu/rocketchat#url
---
type: Secret
api_version: secrets/v1
metadata:
  name: rocketchat_channel
spec:
  provider: vault
  id: secret/sensu/rocketchat#channel
---
type: Asset
api_version: core/v2
metadata:
  annotations:
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/sensu/sensu-rocketchat-handler
    io.sensu.bonsai.name: sensu-rocketchat-handler
    io.sensu.bonsai.namespace: sensu
    io.sensu.bonsai.tags: ""
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/sensu/sensu-rocketchat-handler
    io.sensu.bonsai.version: 0.1.0
  created_by: sensu
  name: sensu/sensu-rocketchat-handler:0.1.0
  namespace: default
spec:
  builds:
  - filters:
    - entity.system.os == 'windows'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: a152e412a4612fff736102ac321e1abc7a2d0de8be1c92143d7f7c515f78c47210e0aa548f7395e3dac41366f2de4d33a876351240a9a74782976fe47b26b8c5
    url: https://assets.bonsai.sensu.io/84d89696e51ce8e3fb7a580721423570afbdd908/sensu-rocketchat-handler_0.1.0_windows_amd64.tar.gz
  - filters:
    - entity.system.os == 'darwin'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: 05063d0dd466da0e4adcbb09255f9ce89f5d9338917577bf1aac68c59d084400d4acdfbe8176fb6a6a2fc173de09b6be075dff16d86b9de9422b666850087012
    url: https://assets.bonsai.sensu.io/84d89696e51ce8e3fb7a580721423570afbdd908/sensu-rocketchat-handler_0.1.0_darwin_amd64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm'
    - entity.system.arm_version == 6
    headers: null
    sha512: fd576a80159e6f68e93256a9d02eb87658ae01f30e0df71c96ae342bc4eb79b0b389d29ce1bbbad87d12fd99e38150a14a302a5ef46860c2ecadd49543f7adc6
    url: https://assets.bonsai.sensu.io/84d89696e51ce8e3fb7a580721423570afbdd908/sensu-rocketchat-handler_0.1.0_linux_armv6.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm'
    - entity.system.arm_version == 7
    headers: null
    sha512: 4f253c0805d48862294dbbee3f398ebb2c4583f3126d2e199b55569e8f41db867631ad4e3bddb590859828a4f3aaa6827283931439b5b59b6e59abe77eceace6
    url: https://assets.bonsai.sensu.io/84d89696e51ce8e3fb7a580721423570afbdd908/sensu-rocketchat-handler_0.1.0_linux_armv7.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'arm64'
    headers: null
    sha512: 492d628a5a1ad3d2d1fcf569c609d32e6dff8d91946afd287690cac25b79022e7f0d101c0de6a832bffaf58f666657ed9702279acf672fbee85d81cc676f3d2a
    url: https://assets.bonsai.sensu.io/84d89696e51ce8e3fb7a580721423570afbdd908/sensu-rocketchat-handler_0.1.0_linux_arm64.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == '386'
    headers: null
    sha512: a2a85376ac9e7e01e23ef4109a45e27b6b865ef452eeb82cf532550b9afa299940a45ef51ccf16072f84dffe11c5c661c750b634d8a8a194253c1ffa99dfca2a
    url: https://assets.bonsai.sensu.io/84d89696e51ce8e3fb7a580721423570afbdd908/sensu-rocketchat-handler_0.1.0_linux_386.tar.gz
  - filters:
    - entity.system.os == 'linux'
    - entity.system.arch == 'amd64'
    headers: null
    sha512: bbe2817c57b8930895b5de479de2466a5aa9f3ee3c131b7a6c373510115dd38c118fe060294c583f92e326082cfa80bd07ed52eb7a116cc9225a3f3c529078d2
    url: https://assets.bonsai.sensu.io/84d89696e51ce8e3fb7a580721423570afbdd908/sensu-rocketchat-handler_0.1.0_linux_amd64.tar.gz
  filters: null
  headers: null
