---
##
# agent configuration
##
backend-url:
- "ws://sensu-backend:8081"
namespace: "default"
# name: demo-agent
subscriptions:
- "docker"
- "poller"
labels:
  region: us-west-1
  demo: https://github.com/calebhailey/sensu-demo
keepalive-interval: 5
keepalive-timeout: 10
deregister: true
#deregistration-handler: "deregister"
#cache-dir: "/var/cache/sensu/sensu-agent"
#config-file: ""
#log-level: "warn"
#redact: ""

##
# authentication configuration
##
#user: "agent"
#password: "P@ssw0rd!"

##
# api configuration
##
api-host: "127.0.0.1"
api-port: 3031
disable-api: false

##
# socket configuration
##
disable-sockets: false
socket-host: "127.0.0.1"
socket-port: 3030

##
# statsd configuration
##
#statsd-disable: false
#statsd-event-handlers: ""
#statsd-flush-interval: 10
#statsd-metrics-host: "127.0.0.1"
#statsd-metrics-port: 8125
