---
type: Asset
api_version: core/v2
metadata:
  namespace: default
  name: event-enrichment-v0.1
spec:
  url: http://sensu-asset-server/assets/event-enrichment-v0.1-linux-x86_64.tar.gz
  sha512: 784e584895d4c61f7d41fd66c9eb28425634e14f01d829fdb67daa94e755aab29d0b3e47dec3b58adb4545b4c12e0021b7eb521a13139d1f5c49c5554046955f

---
type: Asset
api_version: core/v2
metadata:
  namespace: default
  name: nagios_check_http_v0.1
spec:
  url: http://sensu-asset-server/assets/nagios_check_http_v0.1_debian_linux_x86_64.tar.gz
  sha512: fbc385037b202fc3daed546b76ba037715d1f2d6319fec03fb8ca4e97fcd84c716e12be5bf28325f77e47f62d106eaf5784e5e89bed61a01c5c5ee7a3365cd72

---
type: Asset
api_version: core/v2
metadata:
  namespace: default
  name: sensu-influxdb-handler
spec:
  url: https://github.com/sensu/sensu-influxdb-handler/releases/download/3.0.1/sensu-influxdb-handler_3.0.1_linux_amd64.tar.gz
  sha512: 52dd78712a208ca78368d68223e7d4231cad9ed18784c98fdecb29f93fc6581d4264d116cff1324f05041142732af3b485115baa6e6bb512cf17af62da3ee19e

---
type: Asset
api_version: core/v2
metadata:
  namespace: default
  name: sensu-plugins-http
spec:
  url: https://github.com/calebhailey/sensu-plugins-http/releases/download/3.0.1/sensu-plugins-http-3.0.1.tar.gz
  sha512: cd9f3b756e110d5d68af9b9235eb9e38efaf7ea118ce0d6ce2ff1a4049d205e417495c962585d160a534088eb2c1390672116a75c7a667d49cd5fbcf70d102c9

---
type: Asset
api_version: core/v2
metadata:
  namespace: default
  name: sensu-ruby-2.4.4-debian
spec:
  url: https://github.com/sensu/sensu-ruby-asset-builder/releases/download/v0.2/sensu-ruby-2.4.4-debian-linux-x86_64.tar.gz
  sha512: a37e528a7e6c4c976ef7bbc68fe06d8cc1c2ac5944452e0a7e7e742b23a555fdc57510875b6f9c351600d203c91b9f1c5e6039c20b563ab598e539bd96a374f3

---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: sensu_asset_index_response
  labels:
    aggregate: http_service
spec:
  command: check_http -H sensu-asset-server -N
  runtime_assets:
  - nagios_check_http_v0.1
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: nagios_perfdata
  output_metric_handlers:
  - influxdb

---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: check_sensu_io
  labels:
    aggregate: http_service
spec:
  command: "check-http.rb -u https://sensu.io/"
  runtime_assets:
  - sensu-ruby-2.4.4-debian
  - sensu-plugins-http
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: nagios_perfdata
  output_metric_handlers:
  - influxdb

---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: influxdb_metrics
spec:
  command: echo 'web_service value='`echo $RANDOM`' '`date +%s`
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: influxdb_line
  output_metric_handlers:
  - influxdb

---
type: Handler
api_version: core/v2
metadata:
  namespace: default
  name: influxdb
spec:
  type: pipe
  command: "sensu-influxdb-handler -a 'http://influxdb:8086' -d 'sensu' -u 'admin' -p 'admin'"
  timeout: 10
  mutator: event-enrichment
  runtime_assets:
  - sensu-influxdb-handler

---
type: Mutator
api_version: core/v2
metadata:
  namespace: default
  name: event-enrichment
spec:
  command: "transformer"
  timeout: 10
  runtime_assets:
  - event-enrichment-v0.1

