---
##
# agent configuration
##
backend-url:
- "ws://sensu-backend:8081"
organization: "default"
environment: "default"
#id: ""
subscriptions:
- "docker"
- "poller"

##
# authentication configuration
##
#user: "agent"
#password: "P@ssw0rd!"

##
# api configuration
##
api-host: "127.0.0.1"
api-port: 3031
disable-api: false

##
# socket configuration
##
disable-sockets: false
socket-host: "127.0.0.1"
socket-port: 3030

##
# statsd configuration
##
#statsd-disable: false
#statsd-event-handlers: ""
#statsd-flush-interval: 10
#statsd-metrics-host: "127.0.0.1"
#statsd-metrics-port: 8125


##
# other
##
#cache-dir: "/var/cache/sensu/sensu-agent"
#config-file: ""
deregister: true
#deregistration-handler: ""
keepalive-timeout: 60
#keepalive-interval: 20
#custom-attributes: ""
#log-level: "warn"
#redact: ""

##
# extended attributes
##
extended_attributes: "team:ops"
