---
type: CheckConfig
api_version: core/v2
metadata:
  namespace: default
  name: check_sensu_io
  labels:
    aggregate: http_service
spec:
  command: "check-http.rb -u https://sensu.io/"
  runtime_assets:
  - sensu-ruby-2.4.4-debian
  - sensu-plugins-http
  publish: true
  interval: 10
  subscriptions:
  - docker
  output_metric_format: nagios_perfdata
  output_metric_handlers:
  - influxdb
